_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 10
img_size:
    value:
        - 128
        - 128
learning_rate:
    value: 0.001
model:
    value: FoodCNN
