_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 14
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
