name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      # Create raw and processed directories
      - name: Create directories
        run: |
          mkdir -p data/raw
          mkdir -p data/processed

      # Create credentials.json from secret
      - name: Create credentials.json
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          echo $GDRIVE_CREDENTIALS_DATA > credentials.json

      # Modify DVC Remote to use credentials
      - name: Modify DVC Remote
        run: |
          dvc remote modify myremote credentialpath credentials.json

      # Pull DVC-tracked data
      - name: Pull DVC data
        run: |
          dvc pull -v

      # Preprocess Data
      - name: Preprocess Data
        run: python -m src.data preprocess_data 

      # Run tests
      - name: Run tests
        run: pytest tests --cov=src --cov-report=xml
