name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      # Authenticate with Google Cloud using the recommended action
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure gcloud
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Download Test Data
        run: |
          mkdir -p data/raw
          gsutil cp -r gs://foodclassrae/raw/* data/raw/
      
      - name: Create Processed Directory
        run: mkdir -p data/processed

      - name: Preprocess Data
        run: python -m src.data preprocess-data 
        
      - name: Run tests
        run: pytest tests --cov=src --cov-report=xml
