program: src/mlops_project/train.py
name: experiment1
project: "food-classification"
entity: "rasmusarnmark-danmarks-tekniske-universitet-dtu"
method: grid
metric:
    goal: minimize
    name: validation_loss
parameters:
    lr:
        values: [0.001, 0.1]
    batch-size:
        values: [16, 32, 48]
    epochs:
        values: [3, 5, 7]
run_cap: 20